language: node_js
node_js:
- '12'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: avoca-todo
  api_key:
    secure: Xxxu5ZJJ4EUPkcjASNSjZOvpJQUhgVYoSILdbNO0gR4Kv2CzSI9nF6G2t58211UL/PRybfvdhPGsD2HyQ1M2qql+o073i1gKX6QUsb8dSehKzHkLqCDzE8yO1lcrlqf1ZzCXKhfm2+6sMsabhbWL6jNL5qAkWSFtX3TC0v7ped6PX4dgaejczVtDLsNQsychLtdTIKuQ74gdZtIRSKL2LykWPi5pLQr9PHubt5fbqdLErOgzrADcyfecOngXM5C3Bfc4vOFu/YkiQiaud2fXaI1fjbHWqTWVApWKQyvE4No19JdAlKAyDPbPJ2o5OITcGjpdmDxlud4ADsGvE+zyDiJGJZs1nK96k5/U9FIW0vYmTVMvg++3XTZgJkrgw9n6oNcp2FFvQ7tjvES/e/JqphJNeqW3nGJ80fquWbw1vnaWxfg4W6ayeTxTDi96uwjnHpg7F1sWPKyybzSaWy9/n1o1N5gqLtlYP0nYnN82WZUbZcpZJJBYqLNlvURlemJQshDdmM2RHQSp65DQUZPh48AfBfRjmp3T21pAWm1/vDv2jT3yddMZ6lZCZQXHuL1iBj+zhcgQwoHnFYorxO/XrbrUXIG1btDcV9fEyvO8TqKQR3SZTYQ1CjEK8cK2216u96cLwD5qCbyXr7kxgQQuagAuxsZkT18zaFDzXeY5pHI=
