language: node_js
node_js:
- '12'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: avoca-todo
  api_key:
    secure: xDOjvkR5vLnOGk9NZIOkJQcxPBxbMxkXPMjB9m4LjgVvCbDEo3Zk2TvdV8Bb/YjZjdo9B602WUlqinIvgSnnKEqc429hYazw4Yp+LZ+HXbwJO8z5395Yg5A64j9UvDdnJxICEePm6owiSmJnMOITiThFayKQtBiaQDoeoc2gAWYm570qVpmkbCAEIBr2amwFg6J2Zj3jH8vwaIgp26CF1PFnS8Y7twIn3kGNv7StEuiu3PBCq/VkjA+n30whPvWEGjB7PCOKvyyAioUm+s0ujwkQPCmpL0I/NyxztY2R2vlsGiRd4GEm4OMOrH+cgfn40BR0ca4aYPuE95U0Ovfg6EFNuk0l4rvw5oCiPjNfLIvz9Wpk0evOXFOS6U84q73NJDD9VXRH+U0Im0db2azRot4+hChGLbxrz8sMDAEMqZrqoXkceX22j471XfKHmrx4P4aTIGgaPp9PFqVEcHdR5f5e/2SNrhwO3WsaKNOI3HI0k+klMErKf5ho6aTdt2YbWdjTnXq8XnlmscpYMGMYfv09vVSnXMU1S1kwPR+bVQXT8DJV3fQLkc403uerelUnRCbH6pjAVV1I50DDiZNnpCipONVGou6pgXffih9TA5uIK2G5V1/gftvyEiMuLvE+mJAKU4TAg8/0RgYesEbr/knlSJRSzRxXlI9B1mNPiw0=
