language: node_js
node_js:
- '12'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: avoca-todo
  api_key:
    secure: US8Uy4MRO1zeS71e44voS8g6FbJzkuXupwwEAax/OkUA6mefLaW7+Sx94TxukZHC99GFejAd+4/pj9kC/fLBBGLIKEf3GFpUhd1CFoAQ5cTgJGthhEC27N9h6ABEr9nt9a5Ia7wn6zVAyVKUmDpirtEoJkutGUeor0hmWmZxGEn79UYL5/d3X4tkXMlNY3RUaPiDmv2+2yonpFnhoM16wcpo2s1XJbZhp48L9yBREf+gEKZzZDt6bgsMKGSABFseybcnqmmcjLKh0Bg5jLHXlPBYpj8crDEkI7WpC8d+6uk7lf7Mkju0Qlp62cx/noF2HlCa+r+IwIegkiJA0nAiDiODURCgtZIGxJSMIj4vccuKn2+JsgOJn0Z8a6IEo6v52Rc7Smal7hpWRlmM2I9uJuIUZlYFkYoLuOQymfHel3XAJqwp2QELIWoqwQkiA9sDuAqwFexyq/1JvTA+pBhUsLMK3v9ENMjXPmniVYmz+QpmTTm+QoTTI1dJYY+tVS2D0go78A99FaKmjVyvMABrH0bul9x6FOeNI8haKWr67Iuh4UXf7hnrAf7sB/gtyjC6ECzbrwqX+C3afA5XRPWCrUo7yfuoBi8QHaZd+s3iUvVIo2g5ONeliTsKmoLdwvclXe+pafZCMqkErp4QwQY5ZG86AwbJr0yGH3eD5gAsLoQ=
